# Generated by Django 4.2 on 2024-10-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_db', '0002_rank_size_alter_myuser_status_staffprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.IntegerField(choices=[(1, 'ДИРЕКТОР'), (2, 'ТЕХНОЛОГ'), (3, 'ЗАВ СКЛАД'), (4, 'ШВЕЯ')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='status',
            field=models.IntegerField(choices=[(1, 'СОТРУДНИК'), (2, 'КЛИЕНТ')], null=True),
        ),
    ]
